# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 310ab863a4f52b9f452530d78d06abb5bb1a61d8210398f95ab3620fd8669bc5c9402969702e87a4540fd3a81fc01937da67259f2102b42ff31179fce4501c7d

test:
  secret_key_base: 85cafcddd5f990d0a1c0d1b5fdf9d01c1bf2e02c0cd0751bbc4ddf961105c6936ada340644402ad346b7bc65277b4dcaf9e82d9229d117a940633e988bd6d11b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
